[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "selenium-scraper"
version = "v0.0.1"
dependencies = [
  "pandas",
  "numpy",
  "selenium",
  "click"
]
requires-python = ">=3.8"
authors = [
  {name = "Oliver Lybeck", email = "oliver.lybeck94@gmail.com"},
]
maintainers = [
  {name = "Oliver Lybeck", email = "oliver.lybeck94@gmail.com"}
]
description = "Some Selenium Stuff"
readme = "README.md"

[project.optional-dependencies]
gui = ["PyQt5"]
cli = [
  "rich",
  "click",
]

[project.scripts]
run_selenium = "main:run_function"


